name: Update Classes

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  repository_dispatch:
    types: [update_class]

jobs:
  classUpdate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - id: update-src
        uses: metro420yt/class-update@v1
        with:
          folder: src
          ext: css
          diff: "https://raw.githubusercontent.com/SyndiShanX/Update-Classes/main/Changes.txt"
      - id: update-build
        uses: metro420yt/class-update@v1
        with:
          folder: build
          ext: css
          diff: "https://raw.githubusercontent.com/SyndiShanX/Update-Classes/main/Changes.txt"
      - uses: EndBug/add-and-commit@v10
        if: ${{steps.update-src.outputs.totalChanges > 0 || steps.update-build.outputs.totalChanges > 0}}
        with:
          default_author: github_actions
          message: "chore: update classes >_<"
          fetch: true
